"use client";

/**
 * SessionReport — Phase 6 / 3 cross-cut. Generates a take-home PDF
 * summarising a ceremony or solo session: cosmic snapshot, intent,
 * coherence trajectory, and any peak moments captured during the
 * session.
 *
 * jsPDF is loaded via dynamic import so the harness routes don't pay
 * the bundle cost when reports aren't needed.
 */

import { useState } from "react";

export type SessionReportInput = {
  intent: string;
  durationMin: number;
  startedAt: number;
  endedAt: number;
  participantCount?: number;
  coherenceMean?: number;
  depthMean?: number;
  peakMoments?: { at: number; label: string }[];
  cosmicSnapshot?: {
    planetaryHour?: string;
    moonPhase?: string;
    schumann?: string;
  };
  composerSeed?: string;
};

export function SessionReportButton({ input }: { input: SessionReportInput }) {
  const [busy, setBusy] = useState(false);

  const generate = async () => {
    setBusy(true);
    try {
      const mod = await import("jspdf");
      const Pdf = mod.jsPDF;
      const doc = new Pdf({ unit: "pt", format: "a4" });
      const pageW = doc.internal.pageSize.getWidth();
      let y = 60;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(20);
      doc.text("Pinara — session report", pageW / 2, y, { align: "center" });
      y += 30;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      const started = new Date(input.startedAt).toISOString().replace("T", " ").slice(0, 16);
      const ended = new Date(input.endedAt).toISOString().replace("T", " ").slice(0, 16);
      const lines: [string, string][] = [
        ["Intent", input.intent],
        ["Started (UTC)", started],
        ["Ended (UTC)", ended],
        ["Duration", `${input.durationMin} min`],
      ];
      if (input.participantCount != null) lines.push(["Participants", String(input.participantCount)]);
      if (input.coherenceMean != null) lines.push(["Mean coherence", String(Math.round(input.coherenceMean))]);
      if (input.depthMean != null) lines.push(["Mean depth", String(Math.round(input.depthMean))]);
      if (input.cosmicSnapshot?.planetaryHour) lines.push(["Planetary hour", input.cosmicSnapshot.planetaryHour]);
      if (input.cosmicSnapshot?.moonPhase) lines.push(["Moon phase", input.cosmicSnapshot.moonPhase]);
      if (input.cosmicSnapshot?.schumann) lines.push(["Schumann", input.cosmicSnapshot.schumann]);
      if (input.composerSeed) lines.push(["Composer seed", input.composerSeed]);

      for (const [k, v] of lines) {
        doc.text(k, 60, y);
        doc.text(v, pageW - 60, y, { align: "right" });
        y += 18;
      }

      if (input.peakMoments && input.peakMoments.length > 0) {
        y += 16;
        doc.setFont("helvetica", "bold");
        doc.text("Peak moments", 60, y);
        y += 14;
        doc.setFont("helvetica", "normal");
        for (const peak of input.peakMoments.slice(0, 16)) {
          const t = new Date(peak.at).toISOString().replace("T", " ").slice(11, 19);
          doc.text(`${t}  ${peak.label}`, 60, y);
          y += 14;
        }
      }

      y += 28;
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text(
        "Generated by Pinara — pinara.app · Harmonic Waves",
        pageW / 2,
        y,
        { align: "center" },
      );
      doc.save(`pinara-session-${started.replace(/[: ]/g, "-")}.pdf`);
    } catch (err) {
      console.error("Report generation failed:", err);
    } finally {
      setBusy(false);
    }
  };

  return (
    <button
      type="button"
      onClick={() => void generate()}
      disabled={busy}
      className="rounded-full border border-pineal-gold/60 px-4 py-1 text-[11px] uppercase tracking-[0.2em] text-pineal-gold disabled:opacity-50"
    >
      {busy ? "…" : "Export PDF"}
    </button>
  );
}
